server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: eureka-clienta
logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG
