server:
  port: 8761

#配置管理服务器
spring:
  application: 
    name: eureka-server

eureka:
  client:
    register-with-eureka: false # 表示是否将自己注册到Eureka Server，默认为true。
    fetch-registry: false       # 表示是否从Eureka Server获取注册信息，默认为true
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/