server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: eureka-clienta
  zipkin:
    base-url: http://localhost:9600
  sleuth:
    sampler:
#      采样比率，默认0.1，即10%
      percentage: 1.0